// <auto-generated />
namespace API_RentMoto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CodeFirst_Recriar_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CodeFirst_Recriar_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "202508221347341_CodeFirst_Recriar_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
